### ISSUE TITLE
Resize Signature Pad

### ISSUE THREAD

**Issue by brassier** [Mobsites/Blazor.SignaturePad#9]
Hello -

I'm just getting into Blazor for a signature app, and I appreciate this component.  Thank you for your work!

I have a need to capture both a signature and initials.  When capturing initials, I need to present a smaller (square) signature pad.  I didn't immediately see an obvious way to do this with the component, so I used CSS, which works just fine.

However, when saving the signature (`ToDataURL()`), it still has a rectangular shape, half of which is empty.  In looking at the resized signature pad, the `signature-pad`, the `signature-pad--body` and the `signature-pad--canvas` are all square.  

Do you have a suggested way to resize the signature pad without the rectangular results?

**Comment by brassier** [comment]
Looks like the resulting data URLs have the same intrinsic size as this line (700x350).  Would this need to be parameterized in order to adjust this behavior?
https://github.com/Mobsites/Blazor.SignaturePad/blob/fa69c1735289e87bf9d109ce00635b52f5b35fff/src/app.js#L110

**Comment by allan-mobley-jr** [comment]
Appreciate your feedback!

Yes, this is something that should be parameterized. 

Originally, this was not enforced and the signature would be representative of the onscreen representation.

Unfortunately, this caused a problem for a company that in which their employees would turn their phone to get a bigger surface. Yet when they turned their phone back to portrait mode, we found that the signature would get truncated when saving because of the canvas resize (even though the data was still present).

So, for a quick fix, I enforced a canvas size behind the scenes.

But definitely need to address a more optional way of handling different scenarios.

**Comment by cyberdarius** [comment]
> Appreciate your feedback!
> 
> Yes, this is something that should be parameterized.
> 
> Originally, this was not enforced and the signature would be representative of the onscreen representation.
> 
> Unfortunately, this caused a problem for a company that in which their employees would turn their phone to get a bigger surface. Yet when they turned their phone back to portrait mode, we found that the signature would get truncated when saving because of the canvas resize (even though the data was still present).

@allan-mobley-jr Great library !
 I have the same situation.

> So, for a quick fix, I enforced a canvas size behind the scenes.

I'm a web js newbie. How i can enforce the canvas size ? 

Disabling / Force this ?
https://github.com/Mobsites/Blazor.SignaturePad/blob/fa69c1735289e87bf9d109ce00635b52f5b35fff/src/app.js#L127

Thanks

**Comment by allan-mobley-jr** [comment]
@brassier and @cyberdarius 

Sorry, I have been swamped with work lately. I plan to parameterize the hidden canvas dimensions and push a new release this weekend.

As for enforcing a canvas size, the above issue relates to the hidden canvas that is used to save the signature as a data URL or image file. 

The library cannot rely on the signature pad's actual onscreen dimensions because of the situation described above in which part of the signature gets truncated if the device goes from landscape mode to portrait mode.

I did not write the underlying Signature Pad javascript library, just the javascript interop code that abstracts it for Blazor. With that said, I have discovered that by creating a hidden canvas to redraw the signature and setting the canvas size to a predetermined width and length, this truncation can be avoided.

@cyberdarius  As for enforcing a size on the canvas that the is actually seen and used to draw the signature by the user, I believe that you could use CSS and a div tag as a wrapper for the Signature Pad. This is what @brassier has done to make a smaller pad for just initials. However, when saving it, @brassier found that the saved version had the enforced and much bigger background while the signature itself was still small.

**Comment by allan-mobley-jr** [comment]
@brassier and @cyberdarius

The latest release contains the ability to control not only the visual dimensions of the Signature Pad, but the saved dimensions of the signature as well.

Since this addresses this issue, I am closing it now.

Thanks for your feedback and interest!

**Comment by cyberdarius** [comment]
This version fix many things. 

A bug still remain. When saving to SVG in mobile horizontal view the signature is saved cutted.
I think it's a bug of Szymon Nowak's original library :

https://github.com/szimek/signature_pad/issues/478

Png work correctly. I switched to png cause svg il too buggy atm.

Thank you @allan-mobley-jr for your work.

**Comment by allan-mobley-jr** [comment]
Thanks for the heads up on SVG's @cyberdarius!

I'll look into this, but it looks like you have identified the source of the bug.
